### ISSUE TITLE
Reasons for Vega 64 over 5700XT

### ISSUE THREAD

**Issue by hankcs** [reimertz/hackintosh-x570i-5950x#1]
Hi,

Thank you for sharing your recipes on such a cool Hackintosh build. Can I ask for a question if you don't mind?

Could you share your reasons for choosing Vega 64 over 5700XT? According to [some benchmarks](https://gpu.userbenchmark.com/Compare/AMD-RX-Vega-64-vs-AMD-RX-5700-XT/3933vs4045), 5700XT seems to be more powerful and much cheaper.

**Comment by reimertz** [comment]
Hi there @hankcs,

Good question and the answer is very simple; I already had a Vega 64 from my previous EGPU setup. 
And since there where rumors that new gpus coming was about to be released, I didn't buy a new gpu. 

So you are very correct, 5700XT would be better if there weren't new gpus coming out very shortly.

Added a comment regarding this in the overview and will close this.

**Comment by hankcs** [comment]
Thank you so much @reimertz !
